### ISSUE TITLE
[Missing Item] Blue Pencil In Mouth

### ISSUE THREAD

**Issue by ss4w** [GMBoreas/trocalculator#109]
Blue Pencil In MouthID #18819
--
Type: | Armor | Location: | Lower Headgear | Sell: | 10 | Buy: | 20 | Weight: | 10
Defense: | 0 | Required Lvl: | 1 |   |   | Slot: | 0 |   |  
Market: | x | Reward Guru: | 5 TCs | Vanilla: | Yes | Hotlink: |  https://panel.talonro.com/itemdb/18819/
Description: | A blue pencil full of teeth marks due to holding it in your mouth all the time.HIT + 3.
Item script: | [bonus bHit,3;], [], []
Usable on: | Every job

**Comment by GMBoreas** [comment]
Please use the correct format.

**Comment by zonesoldier** [comment]
Item added.
