### ISSUE TITLE
[Missing Item] Cheer Whistle

### ISSUE THREAD

**Issue by ss4w** [GMBoreas/trocalculator#110]
Cheer WhistleID #18837
--
Type: | Armor | Location: | Lower Headgear | Sell: | 10 | Buy: | 20 | Weight: | 10
Defense: | 0 | Required Lvl: | 1 |   | Slot: | 0 |
Market: | x  | Reward Guru: | 5 TCs | Vanilla: | yes | Hotlink: |  https://panel.talonro.com/itemdb/18837/
Description: | Blowing this whistle can drastically improve your team's morale.STR + 1.
Item script: | [bonus bStr,1;], [], []
Usable on: | Every job

**Comment by GMBoreas** [comment]
Please use the correct format.

**Comment by zonesoldier** [comment]
Item Added.
