### ISSUE TITLE
[Missing Item]Loki's Muffler

### ISSUE THREAD

**Issue by zonesoldier** [GMBoreas/trocalculator#112]
ID #2568
Name: Loki's Muffler
Location: garmet
Atk:﻿ N/A
Def: 2
Required Lvl: 95
Slot: 0
Weight: 40
Job: Every job
Description:
A red scarf worn out from long use.

AGI +1

Increases damage inflicted of skill Sonic Blow by 5%.

Unrefineable

**Comment by ss4w** [comment]
ID 2568

**Comment by GMBoreas** [comment]
Please use the correct format.

**Comment by zonesoldier** [comment]
Reopening as i've added the ID tag.

**Comment by zonesoldier** [comment]
Item Added, Issue Closed.
