### ISSUE TITLE
[Wrong Stats] - Fortune Sword

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#118]
_TL;DR:
Change required level from 36 to 24_

Itemid: 1223
Name: Fortune Sword
Location: Daggers
Atk: 90
Lvl: 4
**Required Lvl: 24**
Slot: 0
Weight: 50
Job:
Swordman Mage Archer Merchant Thief Knight
Wizard Blacksmith Hunter Assassin Crusader Sage
Rogue Alchemist Bard/Dancer Soul Linker Ninja
Description:
A knife with a gold handle that is said to bring great fortune to whoever holds it.
Perfect Dodge + 20
LUK + 5

**Comment by zonesoldier** [comment]
Fixed and changed. Thanks for the update!

Issue Closed!
