### ISSUE TITLE
[Wrong Stats] - Carga Mace

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#120]
_TL;DR: 
Should be trans classes only
-Change job id from 71 to 1001_

Itemid: 16003
Name: Carga Mace
Location: Weapon
Atk: 175
Def: 0
Required Lvl: 90
Slot: 2
Weight: 150
**_Job:
Swordman High Acolyte High Merchant High Lord Knight High Priest Whitesmith
Paladin Champion Creator_**
Description:﻿
Its name means 'Great Echo' in the Manuk tribe language, a rugged heavy mace with a sharp edge on one side.

**Comment by zonesoldier** [comment]
You are missing the Level of the items which is 3 in the weapon lvl. 
Location is not weapon is "Mace"

Issue was taken care of. I added the Description and modified the job id. 

Dude you a rocking these tickets. Keep up the level of detail and i can finish your tickets at faster pace.

ZoneSoldier
