### ISSUE TITLE
[Wrong Stats] - Ygnus Stale

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#121]
_TL;DR:
Should be equippable by only trans classes
-Change Job ID from 0 to 1001_

ItemID: 1392
Name: Ygnus Stale [1]
Location: Weapon
Type: Two-handed Axe
Atk: 250
Weapon Lvl: 4
Required Lvl: 95
Slot: 1
Weight: 190
**_Job: Trans Swordman Class, Trans Merchant Class_**
Element: Fire

Description:
A large axe made by a blacksmith from the fires of a volcano.
Chance of inflicting Bleeding status when dealing physical damage. Risk of targeting yourself.
Indestructible (except in upgrade attempts).

**Comment by zonesoldier** [comment]
Item Updated and job id is Fixed. Issue Closed.
