### ISSUE TITLE
[Wrong Stats] - End Sektura

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#122]
_TL;DR:
Should be equippable by only trans classes
-Change Job ID from 0 to 1001
Damage should be 250 not 255_

ItemID: 1393
Name: End Sektura [1]
Location: Weapon
Type: Two-handed Axe
_**Atk: 250**_
Weapon Lvl: 4
Required Lvl: 95
Slot: 1
Weight: 190
_**Job: Trans Swordman Class, Trans Merchant Class**_
Element: Water

Description:
An axe made of artic ice.
Chance of inflicting Curse status when dealing physical damage. Risk of targeting yourself.
Indestructible (except in upgrade attempts).

**Comment by zonesoldier** [comment]
Job ID was changed issue is closed. Thanks dude.
