### ISSUE TITLE
[Missing Monster] - Valhalla Seal Monsters

### ISSUE THREAD

**Issue by gundargerm** [GMBoreas/trocalculator#123]
**==========================================
Prontera Seal
==========================================**
- Wish Maiden - #1931
- Piamette [Angry] - #1930
- Piamette [Slave] - #1947
- Warlock - #2801
- Garden Keeper - #1932
- Garden Watcher - #1933

**==========================================
Manuk Seal
==========================================**
- Halion - #2800
- Nokrah Shadow [Dragon] - #2812

**==========================================
Yuno Seal
==========================================**
- Nokrah [Gunslinger] - #2802
- Nokrah [Warlock] - #2803
- Nokrah [Sorcerer] - #2804
- Nokrah Shadow [Slave] - #2801

**Comment by TensaiKato** [comment]
Done 

Wish Maiden - #1931
Piamette [Angry] - #1930
Piamette [Slave] - #1947
Warlock - #2801

**Comment by TensaiKato** [comment]
Done, awaiting commit

**Comment by TensaiKato** [comment]
Done~
