### ISSUE TITLE
[Missing Monster] - Nightmare Monsters

### ISSUE THREAD

**Issue by gundargerm** [GMBoreas/trocalculator#124]
- Amon Ra [Nightmare] - #2362
- Ancient Mummy [Nightmare] - #2360
- Arclouze [Nightmare] - #2358
- Mimic [Nightmare] - #2356
- Minorous [Nightmare] - #2353
- Mummy [Nightmare] - #2354
- Verit [Nightmare] - #2355

**Comment by nattwara** [comment]
Done
