### ISSUE TITLE
[Missing Monster] - Malangdo Dungeon Monsters

### ISSUE THREAD

**Issue by gundargerm** [GMBoreas/trocalculator#125]
- Wild Rider (#2208) - https://panel.talonro.com/mobdb/2208/
- Pouring (#1894) - https://panel.talonro.com/mobdb/1894/
- Mini Octopus (#2192) - https://panel.talonro.com/mobdb/2192/
- Octopus Leg (#2193) - https://panel.talonro.com/mobdb/2193/
- Giant Octopus (#2194) - https://panel.talonro.com/mobdb/2194/
- Mutant Coelacanth (#2189) - https://panel.talonro.com/mobdb/2189/
- Coelacanth (#2186) - https://panel.talonro.com/mobdb/2186/
- Deep Sea Kukre (#2179) - https://panel.talonro.com/mobdb/2179/
- Deep Sea Obeaune (#2184) - https://panel.talonro.com/mobdb/2184/
- Deep Sea Strouf (#2180) - https://panel.talonro.com/mobdb/2180/
- Deep Sea Sword Fish (#2181) - https://panel.talonro.com/mobdb/2181/
- Deep Sea Anolian (#2183) - https://panel.talonro.com/mobdb/2183/
- Deep Sea Marse (#2175) - https://panel.talonro.com/mobdb/2175/
- Deep Sea Marc (#2182) - https://panel.talonro.com/mobdb/2182/
- Deep Sea Kapha (#2185) - https://panel.talonro.com/mobdb/2185/
- Deep Sea Cornutus (#2177) - https://panel.talonro.com/mobdb/2177/
- Deep Sea Crab (#2176) - https://panel.talonro.com/mobdb/2176/
- Deep Sea Shellfish (#2178) - https://panel.talonro.com/mobdb/2178/
- Deep Sea Vadon (#2174) - https://panel.talonro.com/mobdb/2174/
- Seaweed (#2331) - https://panel.talonro.com/mobdb/2331/ (GMC Gemini Mob)
- Seaweed (#2191) - https://panel.talonro.com/mobdb/2191/

**And there are monsters with Incorrect Property (Based on DB & in-game):**
- Siorava (#2199) - https://panel.talonro.com/mobdb/2199/
- Red Eruma (#2197) - https://panel.talonro.com/mobdb/2197/

**Comment by TensaiKato** [comment]
Did:

Pouring (#1894) - https://panel.talonro.com/mobdb/1894/
Mini Octopus (#2192) - https://panel.talonro.com/mobdb/2192/
Octopus Leg (#2193) - https://panel.talonro.com/mobdb/2193/
Giant Octopus (#2194) - https://panel.talonro.com/mobdb/2194/

**Comment by TensaiKato** [comment]
Done, awaiting commit.

**Comment by TensaiKato** [comment]
Done
