### ISSUE TITLE
Missing Item Set

### ISSUE THREAD

**Issue by mikemike08** [GMBoreas/trocalculator#127]
Please include Aegir Set

Aegir Helm ID#19026
Aegir Armor ID #15138
Aegir Cloak ID #2592
Aegir Shoes ID #2474

**Comment by nattwara** [comment]
I think Kato already added this.

**Comment by mikemike08** [comment]
you mean it has been added to the calc? cant seem to find it there.

**Comment by slaptro** [comment]
The changes we are making aren't live yet on the calc, but I just checked and Kato already added this.
