### ISSUE TITLE
[Missing Monster] - GMC Bosses

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#128]
**Black Talon:** 2682 https://panel.talonro.com/mobdb/2682/

**Boreas:** 2683 https://panel.talonro.com/mobdb/2683/

**Gemini:** 3537 https://panel.talonro.com/mobdb/3537/

**Howl:**
-**Form 1:** 2540 https://panel.talonro.com/mobdb/2540/
-**Form 2:** 2541 https://panel.talonro.com/mobdb/2541/

**Lance:**
-**Form 1:** 3689 https://panel.talonro.com/mobdb/3689/
-**Form 2:** 3690 https://panel.talonro.com/mobdb/3690/
-**Form 3:** 3691 https://panel.talonro.com/mobdb/3691/

**Muui:** 2684 https://panel.talonro.com/mobdb/2684/

**Saen:**
-**Form 1:** 3696 https://panel.talonro.com/mobdb/3696/
-**Form 2:** 3697 https://panel.talonro.com/mobdb/3697/
-**Form 3:** 3698 https://panel.talonro.com/mobdb/3698/

**Seiren:** 2681 https://panel.talonro.com/mobdb/2681/

**Shiris:** 2685 https://panel.talonro.com/mobdb/2685/

**Sushi:** 2680 https://panel.talonro.com/mobdb/2680/

**Comment by TensaiKato** [comment]
Done

**Comment by TensaiKato** [comment]
Done~
