### ISSUE TITLE
[Bug] - Defense reduction formula

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#134]
Current defense reduction formula (24 after item description) for item effects only reduces hard defense (bDef) but not soft defense (bDef2).

Item scripts for items with defense reduction dictate that soft defense (bDef2) is affected as well. See Grimtooth (ID[1237](https://panel.talonro.com/itemdb/1237/)), Masamune (ID[1165](https://panel.talonro.com/itemdb/1165/)), and Spike(ID[1523](https://panel.talonro.com/itemdb/1523/), [1538](https://panel.talonro.com/itemdb/1538/)).

Formula is in foot.js line 1143, probably.

**Comment by TensaiKato** [comment]
Found the issue, will work on these items, not all Defense reductions have bDef2, so I will just commit these changes and other items you find I will fix aswell.

**Comment by TensaiKato** [comment]
Done, awaiting commit

**Comment by TensaiKato** [comment]
Done
