### ISSUE TITLE
[Proofreading] - ItemOBJ indices [0-70]

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#135]
Proofreading the item array in item.js starting from the top. Will document errors I can fix here and in change log. Will create new issues for things I can't handle.

Changes:
		Jeweled Sword: updated item description
		Gaia Sword: updated item description
		Saber: name (Sabre -> Saber)
		Cutlus: weight (30 -> 90)
		Mysteltainn: attack (160 -> 170)
		Katzbalger: effect (VIT+10 -> VIT+5)
		Javelin: name (Javalin -> Javelin)
		Gungnir: required lvl (48 -> 4)
		Halberd: name (Hallberd -> Halberd) //to match itemdb
		Axe: jobid (50 -> 0)
		Orcish Axe: jobid (72 -> 0)
		War Axe: attack (145 -> 140)

**Comment by TensaiKato** [comment]
@slaptro Are you doing Pull Requests later or do you want to share your codes so we fix?

**Comment by slaptro** [comment]
I'm just checking everything is in order before I push/create my branch before doing a pull request.
