### ISSUE TITLE
[Missing Item] - Burning Crown

### ISSUE THREAD

**Issue by marxtrinidad** [GMBoreas/trocalculator#14]
Name: Burning Crown (#20175)
Location: Upper Headgear
Def: 3
Required Level: 1
Slots: 0
Weight: 50
Applicable Job: Every job
Description:
Add a 1.5% chance of auto casting Level 3 Bash on an enemy when doing Physical damage.
Increases resistance to Fire Property by 20%.
Increase damage inflicted upon Earth Property enemies by 20%.

Item Script: 
[bonus2 bSubEle,Ele_Fire,20; bonus2 bAddEle,Ele_Earth,20; bonus3 bAutoSpell,"SM_BASH",3,15;], [], []

**Comment by TensaiKato** [comment]
Done, awaiting commit.

**Comment by TensaiKato** [comment]
Commited
