### ISSUE TITLE
[Proofreading] - ItemOBJ

### ISSUE THREAD

**Issue by Loabox** [GMBoreas/trocalculator#149]
Proofreading ItemOBJ Slowly. Will also make a local file at request of Kato that links ID in ItemOBJ to in game item ID. Am also updating item names to those used in the item database instead of iRO translations.

**Comment by slaptro** [comment]
Done indices 0-250.

**Comment by TensaiKato** [comment]
Item proof will also handle the ItemID upgrade for the link :)

**Comment by slaptro** [comment]
Proofreading progress (400/1660). ItemID array for links will be generated by script once all proofreading has been done.

**Comment by slaptro** [comment]
Proofreading progress (500/1662)
