### ISSUE TITLE
[Wrong effect/status] - Anubis hat

### ISSUE THREAD

**Issue by terenzi94** [GMBoreas/trocalculator#15]
the item in the calc gives +10% for boss resist and heal amount, but its only 3%.
Name: Anubis Hat
Location: Upper Headgear
Atk: N/A
Def: 3
Slot: 0
Required Lvl: 70
Job: Every Job
Description: 
This ceremonial headdress holds the likeness of Anubis, god of the underworld.

It is rumored that it empowers the wearer against powerful divine beings.

Reduce damage from MVPs by 3%.

Increase effectiveness of healing and healing items by 3%.

**Comment by TensaiKato** [comment]
Done, awaiting commit.

**Comment by TensaiKato** [comment]
Commited
