### ISSUE TITLE
Card set selector not working properly

### ISSUE THREAD

**Issue by nattwara** [GMBoreas/trocalculator#154]
-Selected 2x Race, Got 3TG
![chrome_2018-06-08_11-31-54](https://user-images.githubusercontent.com/3313046/41139257-ba85fa50-6b10-11e8-95a0-9d270e71bebd.png)

- Duplicated Job Card Set
![chrome_2018-06-08_11-31-44](https://user-images.githubusercontent.com/3313046/41139256-ba539ea2-6b10-11e8-9ee2-6b764f99ebe8.png)

Blank instead of "No Card" which stop further calculation until user select the Blank and put something else in it.
![chrome_2018-06-08_11-39-25](https://user-images.githubusercontent.com/3313046/41139255-ba20d9cc-6b10-11e8-801c-a82bc5e16a0d.png)

Ex: try picking a weapon while it's blank, no atk added, description box didn't updated to show weapon info.
![chrome_2018-06-08_11-44-57](https://user-images.githubusercontent.com/3313046/41139387-7680b84e-6b11-11e8-9991-8cb988d91106.png)

Ps. grey color is temporary.

**Comment by TensaiKato** [comment]
Thanks
