### ISSUE TITLE
[Missing Item] - Guillotine Katar

### ISSUE THREAD

**Issue by marxtrinidad** [GMBoreas/trocalculator#16]
Name: Guillotine Katar (#1291)
Location: Weapon
Type: Katar
Attack: 190
Weapon Level: 4
Required Level: 95
Slots: 1
Weight: 150
Applicable Job: Assassin Cross
Description:
A Katar used by Guillotine Cross to punish traitors within the guild.
Increases damage to Demihuman monsters by 25%.
Increases damage of Sonic Blow by 15%.
DEX + 2. Decreases FLEE by 30.

Item script:
[bonus bDex,2; bonus bFlee,-30; bonus2 bAddRace,RC_DemiHuman,25; bonus2 bSkillAtk,"AS_SONICBLOW",15;], [], []

**Comment by TensaiKato** [comment]
Done, awaiting commit.

**Comment by TensaiKato** [comment]
Commited
