### ISSUE TITLE
[Feature Request] ItemID Display

### ISSUE THREAD

**Issue by Rorb** [GMBoreas/trocalculator#161]
TL;DR: http://i.imgur.com/FvxmT97.png  

Description: https://forum.talonro.com/suggestions/show-item-ids-in-stat-calculator-r985/

**Comment by nattwara** [comment]
Added show Item ID template.

Currently only these item have correct ID in item.js
-Enhanced Hat of the Sun God
-Enhanced Helm of Angel
-Enhanced Bone Helm
-Enhanced Corsair
-Lord of the Dead Helm

And Chilly Spell Book have "Test Item ID Display - Chilly Spell Book" in place of Item ID

Everything else have "###" as Item ID placeholder for now.

**Comment by slaptro** [comment]
Added first 251 items to the ItemID array for creating links in item.js. This will take a while as these ID have to be added manually at the moment. See #165

**Comment by TensaiKato** [comment]
It's done and will be upgraded as we can add the references
