### ISSUE TITLE
[Missing Item] - Aegir Armor

### ISSUE THREAD

**Issue by marxtrinidad** [GMBoreas/trocalculator#17]
Name: Aegir Armor (#15138)
Location: Armor
Def: 5
Slot: 1
Required Lvl: 40
Job: Every Job
Weight: 160
Description:
Aegir, the God of Sea's Armor. It has a shape of a beautiful mermaid and seems to enable wearer swim in the water.

MaxHP + 500, MaxSP + 50.

Indestructible except in upgrade attempts.

[+ Aegir Helm Combo]

Decreases damage from Fish type monsters by 10%.

Additional decrease of damage by 1%, per refinement of the armor.

Item Script:
[bonus bMaxHP,500; bonus bMaxSP,50; bonus bUnbreakableArmor,1; if(isequipped(19026)) { bonus2 bSubRace,RC_Fish,(10+getequiprefinerycnt(EQI_ARMOR)); }], [], []

**Comment by TensaiKato** [comment]
Done, awaiting commit.

**Comment by TensaiKato** [comment]
Commited
