### ISSUE TITLE
[Missing Item] "Party Hat" (party recruit hat)

### ISSUE THREAD

**Issue by nattwara** [GMBoreas/trocalculator#170]
Missing party hat, the one with "party wanted" sign.
https://panel.talonro.com/itemdb/5337/

The party hat in our calc is this one:
[370,50,0,3,0,0,30,0,"Party Hat","",0,6,1,0]
https://panel.talonro.com/itemdb/5060/

**Comment by TensaiKato** [comment]
Done

**Comment by TensaiKato** [comment]
Commited
