### ISSUE TITLE
Report for Item-IDs

### ISSUE THREAD

**Issue by nattwara** [GMBoreas/trocalculator#171]
Item in calc, [ID in TRO's DB]

524,[2659]
525,[2660]
526,[2661]
527,[2662]
1321,[1728]
1322,[1388]
1323,[1829]
1324,[1580]
1325,[1929]
1326,[1286]
1327,[1487]
1328,[1983]
1329,[16002]
1330,[1373]
1331,[1273]
1332,[1744]
1333,[1424]
1334,[13021]
1335,[13401]
1336,[13408]
1337,[1378]
1338,[1567]
1339,[13409]
1340,[1267]
1341,[1817]
1342,[1283]
1343,[1547]
1344,[13025]
1345,[1623]
1346,[1828]
1347,[1173]
1348,[13407]
1349,[1982]
1350,[1578]
1351,[1537]
1352,[1427]
1353,[1642]
1354,[1638]
1355,[1628]
1356,[13024]
1357,[1274]
1358,[2696]
1359,[2697]
1360,[2698]
1361,[2699]
1362,[2385]
1363,[2439]
1364,[2543]
1365,[2535]
1366,[2710]
1367,[2711]
1368,[5331]
1369,[5279]
1370,[5268]
1371,[5326]
1375,[1290]
1376,[2150]
1377,[1745]
1378,[1990]
1379,[1190]
1380,[1320]
1382,[1549]
1383,[2480]
1384,[1651]
1385,[13320]
1386,[1430]
1387,[5600]
1388,[1746]
1389,[1650]
1390,[1840]
1391,[1590]
1394,[18643]
1395,[5597]
1396,[18566]
1397,[18642]
1398,[18644]
1400,[18677]
1404,[18678]
1405,[18670]
1406,[5445]
1407,[18564]
1408,[18563]
1410,[5210]
1411,[18703]
1412,[18536]
1414,[5548]
1416,[18683]
1419,[18648]
1423,[5664]
1424,[5822]
1425,[5171]

**Comment by TensaiKato** [comment]
Done

**Comment by TensaiKato** [comment]
Also did 1605 to 1661

**Comment by TensaiKato** [comment]
Commited
