### ISSUE TITLE
Name of items in calc doesn't matched TRO's DB

### ISSUE THREAD

**Issue by nattwara** [GMBoreas/trocalculator#172]
Calc -> TRO's DB

Dulga -> Durga
Lapine -> Laphine
Death Loop -> Death Medalion
Rune Spellstone -> Rune Charm Stone
Bloody Shackle Ball R -> Bloodied Shackle Ball R
Minor Valkyrian Helm -> Minor Valkyrie Helm
Valkyrian Shield -> Valkyrja's Shield
Valkyrian Armor -> Valkyrja's Armor
Valkyrian Manteau -> Valkyrja's Manteau
Valkyrian Shoes -> Valkyrja's Shoes
Sword Breaker R -> Swordbreaker R
Mail Breaker R -> Mailbreaker R
Mail Breaker -> Mailbreaker
Bf Recruiter Cap -> Boyfriend Hat
Gf Recruiter Cap -> Girlfriend Hat
Guildsman Cap -> Guild Member Hat
Friend Recruiter Hat -> Friend Hat

**Comment by TensaiKato** [comment]
Done (some of them were OK)

**Comment by TensaiKato** [comment]
Commited
