### ISSUE TITLE
Luna Kaleet Wrong Description

### ISSUE THREAD

**Issue by nattwara** [GMBoreas/trocalculator#173]
Item : ID 1544

Calc:
When a Brute is killed, 15% chance to drop +4 STR Food
When a Plant is killed, 15% chance to drop +5 DEX Food
When a Fish is killed, 15% chance to drop +3 LUK Food

TRO DB:
Brute/Fish 5%
Plant 0.5%

**Comment by TensaiKato** [comment]
Done~

**Comment by TensaiKato** [comment]
Commited
