### ISSUE TITLE
[Missing Item] - Aegir Cloak

### ISSUE THREAD

**Issue by marxtrinidad** [GMBoreas/trocalculator#18]
Name: Aegir Cloak (#2592)
Location: Garment
Def: 2
Slot: 1
Required Lvl: 40
Job: Every Job
Weight: 30
Description:﻿
Aegir, the God of Sea's Garment. It is said to protect wearer with sacred power of the Sea.

MaxHP + 500, MaxSP + 50.

Indestructible except in upgrade attempts.

[+ Aegir Helm Combo]

Recovers 10 SP every time you kill a Fish type monster.

Add a chance to drop Sushi or Raw Fish when killing a Fish type monster, which increases per refine.

Sushi and Raw Fish's HP recovery increases by 5%.

Increases natural HP recovery by 5% per refine.

Item Script:
[bonus bUnbreakableGarment,1; bonus bMaxHP,500; bonus bMaxSP,50; if(isequipped(19026)) { set .@r,getequiprefinerycnt(EQI_GARMENT); bonus2 bSPGainRace,RC_Fish,10; bonus3 bAddMonsterDropItem,551,RC_Fish,(5+.@r); bonus3 bAddMonsterDropItem,544,RC_Fish,(5+.@r); bonus2 bAddItemHealRate,551,5; bonus2 bAddItemHealRate,544,5; bonus bHPrecovRate,(5+.@r); }], [], []

**Comment by TensaiKato** [comment]
Done, awaiting commit.

**Comment by TensaiKato** [comment]
Commited
