### ISSUE TITLE
[Missing Item] - Aegir Helm

### ISSUE THREAD

**Issue by marxtrinidad** [GMBoreas/trocalculator#19]
Name: Aegir Helm (#19026)
Location: Upper-Only Headgear
Def: 2
Required Lvl: 40
Job: Every Job
Weight: 80
Description:
Aegir, the God of Sea's Helm. When all set items are combined, it gives you the power of the Sea.

VIT + 3.

[+ Aegir Armor & Aegir Shoes & Aegir Cloak Set Combo]

MaxHP + 1000, MaxSP + 100

EXP+20% when defeating Fish type monsters.

Increases physical and magical damage to Fish type monsters by 50%.

Decreases damage from Water element attacks by 30%.

Item Script:
[bonus bVit,3; if(isequipped(15138,2474,2592)) { bonus bMaxHP,1000; bonus bMaxSP,100; bonus2 bExpAddRace,RC_Fish,20; bonus2 bAddRace,RC_Fish,50; bonus2 bMagicAddRace,RC_Fish,50; bonus2 bSubEle,Ele_Water,30; }], [], []

**Comment by TensaiKato** [comment]
Done, awaiting commit.

**Comment by TensaiKato** [comment]
Commited
