### ISSUE TITLE
[Missing Item] - Cat Club

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#191]
Cat Club [3]
ID #16015

Class: Mace
Weight: 70
Attack: 88
Required lvl: 1
Weapon lvl: 1
Slot: 3

Job: Novice , Swordman Class, Acolyte Class, Merchant Class

A cat hand shaped club which doesn't seem hurt.
Increases physical damage against Brute monsters by 15%.
Has a chance of casting [Wink of Charm] while physically attacking.

**Comment by TensaiKato** [comment]
Done~
