### ISSUE TITLE
[Missing Item] - Aegir Shoes

### ISSUE THREAD

**Issue by marxtrinidad** [GMBoreas/trocalculator#20]
Name: Aegir Shoes (#2474)
Location: Footgear
Def: 3
Required Lvl: 40
Job: Every Job
Weight: 30
Description:
Aegir, the God of Sea's Shoes. It seems to strengthen one's weakness.

MaxHP + 500, MaxSP + 50.

Indestructible except in upgrade attempts.

[+ Aegir Helm Combo]

Increases CRIT by 10 against Fish type monsters.

Increases CRIT against Fish type monsters by 1%, per refinement of the Shoes.

Item Script:
[bonus bUnbreakableShoes,1; bonus bMaxHP,500; bonus bMaxSP,50; if(isequipped(19026)) { bonus2 bCriticalAddRace,RC_Fish,(10+getequiprefinerycnt(EQI_SHOES)); }], [], []

**Comment by TensaiKato** [comment]
Done, awaiting commit.

**Comment by TensaiKato** [comment]
Commited
