### ISSUE TITLE
Sage book options

### ISSUE THREAD

**Issue by SkyF1st** [GMBoreas/trocalculator#201]
Eden katar I and Eden Knuckles I as a sage book options should be removed.
p.s.: and moved to monk and assassin respectively.

![sagekatarknuckles](https://user-images.githubusercontent.com/40445265/41691836-855430b4-7505-11e8-9d46-1cf2ff573882.png) 
![katar sage](https://user-images.githubusercontent.com/40445265/41691834-844e367e-7505-11e8-88d4-709eee528b86.png)       ![sage knuckles](https://user-images.githubusercontent.com/40445265/41691835-84d5a03c-7505-11e8-99ab-6f8bf230f831.png)

**Comment by TensaiKato** [comment]
Done~
