### ISSUE TITLE
Baby Leopard pet wrong stats

### ISSUE THREAD

**Issue by SkyF1st** [GMBoreas/trocalculator#202]
[Has to give 5%.](https://panel.talonro.com/itemdb/9203/)
Only adds [3% in calc.](https://user-images.githubusercontent.com/40445265/41692022-6f9ff144-7506-11e8-8994-010528e14767.png)

**Comment by TensaiKato** [comment]
Fixed, awaiting commit

**Comment by TensaiKato** [comment]
Done~
