### ISSUE TITLE
List of mid headgears to change.

### ISSUE THREAD

**Issue by SkyF1st** [GMBoreas/trocalculator#206]
- [x] Tongue-Sticking Mask - wrong ID, no description and effects. Probably real one this "5272"
- [ ] Tiger face - adds only 5% physical dmg. Has to add 5% p.dmg/m.dmg. Description. Wrong ID.
- [ ] Hahoe Mask - Change ID. Add description.
- [ ] Cube Mask - Change ID. Add description. 1121 > 5475
- [ ] Blush of Groom - Change def from 6 to 0.

What about removing useless items?
Takius Blindfold - 0def no effect
Blank Eyes - 0def no effect
Glasses - 0def no effect
Eye Patch - 0def no effect
Elven ears - 0def no effect
Diver Goggles - 0def no effect

**Comment by slaptro** [comment]
I don't think we will be removing purely cosmetic items as we want to accurately represent what you can obtain in-game.

**Comment by slaptro** [comment]
Sorting items by stats isn't the purpose of the calculator. It's best to use the control panel to search for items first. Otherwise if you suspect something is missing, definitely let us know.
