### ISSUE TITLE
[Missing Item] - Red Square Bag [2]

### ISSUE THREAD

**Issue by Tomz295** [GMBoreas/trocalculator#21]
Name: Red Square Bag (#16001)
Type: Mace
Attack: 130
Weapon Level: 3
Required Level: 50
Slots: 2
Weight: 50 
Description:﻿
The official suitcase of the Alchemist's society. Its unique design and blazing red colour is a hit amongst women.

MaxHP + 200

Increases damage when using skill Acid terror or Demontration by 20%.

[Base Strength >= 90]

A chance to Stun status by 5%.

Every time you kill a monster, low chance to drop random Potion.

Item Script: **TRO Database ItemScript is wrong, but here it goes anyways**
[bonus bMaxHP,200; bonus2 bSkillAtk,"AM_ACIDTERROR",20; bonus2 bSkillAtk,"AM_DEMONSTRATION",20; bonus2 bAddMonsterDropItem,501,50; bonus2 bAddMonsterDropItem,502,20; bonus2 bAddMonsterDropItem,503,20; bonus2 bAddMonsterDropItem,504,20; bonus2 bAddMonsterDropItem,505,10; if(readparam(bStr)>=95) bonus2 bAddEff,Eff_Stun,500;], [], []

**Comment by TensaiKato** [comment]
Done, awaiting commit.

**Comment by TensaiKato** [comment]
Commited
