### ISSUE TITLE
[Missing Item] - Reforged Lord Kaho's Horns

### ISSUE THREAD

**Issue by Tomz295** [GMBoreas/trocalculator#22]
_Not to be mistaken with the real Lord Kaho Horns. These are the ones given in the middle of the LKH quest._

Name: Reforged Lord Kaho's Horns (#8926)
Location: Upper Headgear
Def: 2
Slot: 0
Required Lvl: 0
Job: Every Job
Weight: 0
Description:﻿
Reforged Horns Of Lord Kaho. You feel a strange power emitting from them but they are not quite complete yet.

STR + 5 , INT + 5

DEX + 5 , MDEF + 5

Cannot be refined.

Item Script:
[bonus bMdef,5; bonus bStr,5; bonus bInt,5; bonus bDex,5;], [], []

**Comment by TensaiKato** [comment]
Commited
