### ISSUE TITLE
Wrong item stats - Electric guitar ID #1913

### ISSUE THREAD

**Issue by ShaIIia** [GMBoreas/trocalculator#224]
Itemid: 1913
Name: Electric Guitar
Location: Weapon
Class: Instrument
Atk: 190
Def: N/A
Element: Wind
Weapon lvl: 4
Required Lvl: N/A
Slot: 3
Weight: 100
Job: Bard
Description: A guitar with the soul of a demon songstress. The melodies produced by this guitar send shockwaves of electricity through the enemy.

Enchanted With Lightning.

DEX + 5, INT + 4, VIT + 4.

This item can be upgraded with bonuses.

Actually calc doesn't include stats, attack and weapon lvl.

**Comment by slaptro** [comment]
This is fixed somewhere in #222
