### ISSUE TITLE
Missing items - Sheila hairnets

### ISSUE THREAD

**Issue by ShaIIia** [GMBoreas/trocalculator#225]
Itemid:18587
Name: Blue Sheila Hairnet
Location: Upper headgear
Def: 0
Required Lvl: 1
Slot:1
Weight:1
Job: every job
Description:	A hairband that attracts men.

You can wear it when you want to look sexy. Your sexiness increases to 100%.

VIT + 2, INT + 1, STR + 3.

[Refine Rate 9~10]

Increase ATK and MATK by 2%.

[Refine Rate 10]

Reduce casting time by 10%.

----------------------------------------------------------------------

Itemid: 5785
Name: Green sheila hairnet
Location: Upper headgear
Def: 0
Required lvl: 1
Slot: 1
Weight: 20
Job: every
Description: 	A hairband that attracts men.

You can wear it when you want to look sexy. Your sexyness increases to 100 %.

STR + 2, INT + 1, DEX + 1,

[Refine Rate 9~10]

Increase ATK and MATK by 2%.

[Refine Rate 10]

Increase ATK and MATK by 2% in addition.

----------------------------------------------------------------------

Itemid: 18585
Name: Orange sheila hairnet
Location: Upper headgear
Def: 0
Req lvl: 1
Slot: 1
Weight: 1
Job: every
Description: A hairband that attracts men.

You can wear it when you want to look sexy. Your sexiness increases to 100%.

VIT + 3, INT + 2, STR + 1.

[Refine Rate 9~10]

Increase ATK and MATK by 2%.

[Refine Rate 10]

Reduce casting time by 10%.

----------------------------------------------------------------------

Itemid: 5784
Name: Pink sheila hairnet
Location: Upper headgear
Def: 0 
Req lvl: 1
Slot: 1
Weight: 20
Description: A hairband that attracts men.

You can wear it when you want to look sexy. Your sexyness increases to 100 %

STR+ 1, INT + 2, DEX + 1,

[Refine Rate 9~10]

Increase ATK and MATK by 2%.

[Refine Rate 10]

Increase ATK and MATK by 2% in addition.

----------------------------------------------------------------------

Itemid: 5763
Name: Red sheila hairnet
Location: Upper headgear
Def: 2
Req lvl: 1
Slot: 0
Weight: 20
Description: 	A hairband that attracts men.

You can wear it when you want to look sexy.

Your sexyness increases to 100 %

AGI + 2, MDEF+3

----------------------------------------------------------------------

Itemid: 5213
Name: Sheila hairnet
Location: Upper headgear
Def: 2
Req lvl: 1
Slot: 0
Weight: 20
Description: Hair lace specially designed for the sexy you!

You will capture the attention of other males when you wear it Sexy rating will be increased by 100%.

AGI + 2, MDEF + 3

----------------------------------------------------------------------

Itemid: 18588
Name: Silver sheila hairnet
Location: Upper headgear
Def: 0 
Req lvl: 1
Slot: 1
Weight: 1
Description: A hairband that attracts men.

You can wear it when you want to look sexy. Your sexiness increases to 100%.

VIT + 1, INT + 3, STR + 2.

[Refine Rate 9~10]

Increase ATK and MATK by 2%.

[Refine Rate 10]

Reduce casting time by 10%.

----------------------------------------------------------------------

Itemid: 18586
Name: Violet sheila hairnet
Location: Upper headgear
Def: 0
Req lvl: 1
Slot: 1
Weight: 1
Description: 	A hairband that attracts men.

You can wear it when you want to look sexy. Your sexiness increases to 100%.

VIT + 2, INT + 3, STR + 1.

[Refine Rate 9~10]

Increase ATK and MATK by 2%.

[Refine Rate 10]

Reduce casting time by 10%.

----------------------------------------------------------------------

Itemid: 5783
Name: Yellow sheila hairnet
Location: Yellow sheila hairnet
Def: 0
Req lvl: 1
Slot: 1
Weight: 20
Description: 	A hairband that attracts men.

You can wear it when you want to look sexy. Your sexyness increases to 100 %.

STR + 1, INT + 1, DEX + 2,

[Refine Rate 9~10]

Increase ATK and MATK by 2%.

[Refine Rate 10]

Increase ATK and MATK by 2% in addition.

**Comment by slaptro** [comment]
See #234
