### ISSUE TITLE
[Feature Suggestion] - Cannot choose Pot Pitcher & Slim Pot Pitcher Level independent from the Potion used

### ISSUE THREAD

**Issue by Tomz295** [GMBoreas/trocalculator#23]
What this means is that you cannot test, for example, Condensed Red/Yellow Pots with lvl 10 Slim Pot Pitcher, or Non-White potions with lvl 5 Pot Pitcher, in which in both cases Max learned Level affects the effectiveness of the potion used.

I suggest separating both normal and slim pot pitcher sliders into 2 different sliders each:
- Learnt Level (for the effectiveness% bonus)
and
- Potion Thrown

**Comment by kutsuru** [comment]
This request should have been solved with following commit
https://github.com/GMBoreas/trocalculator/commit/cfbaa72201aee8af35c97928736780d9c26c41c8
