### ISSUE TITLE
[Missing Item] - Advanced Fin Helm

### ISSUE THREAD

**Issue by gundargerm** [GMBoreas/trocalculator#24]
**Name:** Advanced Fin Helm (#18773)
**Def:** 2
**Slot:** 0
**Location:** Middle Headgear
**Required Lvl:** 65
**Job:** Swordman Class
**Weight:** 30
**Description:**
Maximum HP + 300.
Additional Maximum HP + 6 * Base Level.

**Item Script:**
[bonus bMaxHP,300+(BaseLevel*6);], [], []

**Comment by TensaiKato** [comment]
Done, awaiting commit.

**Comment by TensaiKato** [comment]
Commited

**Comment by gundargerm** [comment]
![bug_2](https://user-images.githubusercontent.com/6234402/41267630-64963736-6e26-11e8-8d39-430b17d5a8c6.JPG)
