### ISSUE TITLE
[Malangdo Enchant] - Some enchant not available on some weapon in calc, but exist in game.

### ISSUE THREAD

**Issue by nattwara** [GMBoreas/trocalculator#246]
INT+3 can't be choosen for rods.
But there exist Dark Thorn Staff and Divine Cross with INT+3 enchant.

**Comment by Loabox** [comment]
Int+3 works fine for rods. DTS can't have int+3. See https://wiki.talonro.com/Malangdo_Enchantments at the bottom.

**Comment by nattwara** [comment]
I can confirm DTS can have INT+3, as well as Divine Cross.
Or did I missed some update?

![screentalonro267](https://user-images.githubusercontent.com/3313046/42697418-43c93774-86e5-11e8-9119-879bed0bedda.jpg)

![screentalonro268](https://user-images.githubusercontent.com/3313046/42697422-4648aba6-86e5-11e8-8709-f938ae68a9d3.jpg)
