### ISSUE TITLE
[Missing Item] - Lude Mask

### ISSUE THREAD

**Issue by gundargerm** [GMBoreas/trocalculator#25]
**Name:** Lude Mask (#18649)
**Def:** 2
**Slot:** 1
**Location:** Middle, Lower Headgear
**Required Lvl:** 50
**Job:** All Job
**Weight:** 50

**Description:**
ATK + 1%.
MATK + 2%.
Decreases damage from [Demi-Human] race monsters by 1%.

**Item Script:**
[bonus2 bAddRace,RC_NonBoss,1; bonus2 bAddRace,RC_Boss,1; bonus bMatkRate,2; bonus2 bSubRace,RC_DemiHuman,1; bonus2 bAddMonsterDropItem,12192,50;], [], []

**Comment by zonesoldier** [comment]
Added. Closing Issue.
