### ISSUE TITLE
[BUG] Issue with item and enchant that give +ATK% (probably everything else that give +ATK%)

### ISSUE THREAD

**Issue by nattwara** [GMBoreas/trocalculator#252]
These item don't show extra ATK in-game, and their actual script are bAddRace,RC_Boss,1 & bAddRace,RC_NonBoss,1 (Same script as TG card)

Current item I've discovered so far.
-Chewing bubblegum ID#5597
https://panel.talonro.com/itemdb/5597/
-Ancient Gold Adornment ID#18570
https://panel.talonro.com/itemdb/18570/
-Rainbow Poring hat ID#18790
https://panel.talonro.com/itemdb/18790/

In the calculator, some of the code were adding P_ATK += P_ATK * 0.01 which isn't what the actual script is doing.

I've also tested out with a knight with 192 atk + eden spear 165 atk with +2% ATK enchant, the result is exactly 357, no +2% ATK what so ever.

The ATK on status window must not increase with this as well.
I've also confirm with other player who have Chewing bubblegum and he confirm the ATK on status window doesn't increase neither.

However if it were the case of using TG script, the ATK will not shown and will use n_tok[80] to add attack power.

Need re-checking on all item saying +ATK%
Including +ATK% enchants.

**Comment by nattwara** [comment]
Currently doing enchants.
I'll get on this after I'm done with enchants. Maybe by tomorrow or Saturday. Or if anyone could help with this issue that would be great. :)

**Comment by nattwara** [comment]
For now I put "//Note - Issue#252" in the code in foot.js and head.js to mark things that need checking.

**Comment by Loabox** [comment]
My fault for not putting an issue up earlier. This was something I didn't notice until very late in proofreading. All items and enchants that affect ATK% should be using n_tok[80] except for 5: Hermose Cap, Angel of Ghost, and 3 of the Sheila Hats. These 5 should either use n_tok[87] or have custom code in foot.js.

**Comment by nattwara** [comment]
Ok, I change then to n_tok[80] for now.
And the item you mentioned are using n_tok[87]

**Comment by TensaiKato** [comment]
Commited~
