### ISSUE TITLE
[Missing Item] - Xmas Rudolph Hairband

### ISSUE THREAD

**Issue by gundargerm** [GMBoreas/trocalculator#26]
**Name:** Xmas Rudolph Hairband (#20031)
**Def:** 4
**Slot:** 0
**Location:** Upper Headgear
**Required Lvl:** 30
**Job:** All Job
**Weight:** 20

**Description:**
STR + 3.
DEX + 2.
LUK + 3.
AGI + 3.
ASPD + 5%.
Movement speed increased (same as Increase AGI).

**Item Script:**
[bonus bStr,3; bonus bDex,2; bonus bLuk,3; bonus bAgi,3; bonus bSpeedRate,25; bonus bAspdRate,5;], [], []

**Comment by zonesoldier** [comment]
Added, Closing Issue.
