### ISSUE TITLE
[Updated Items] Battleground Equips

### ISSUE THREAD

**Issue by Loabox** [GMBoreas/trocalculator#263]
List [here](https://forum.talonro.com/topic/28827-updates-battlegrounds-release/?tab=comments#comment-267315) in spoilers near bottom. All these items exist in ItemOBJ but are the old entries. A lot of battleground equips have had names updated. These changes are not yet reflected in panel.

**Comment by TensaiKato** [comment]
Refer to the Wiki: https://wiki.talonro.com/Battlegrounds

**Comment by TensaiKato** [comment]
Commited
