### ISSUE TITLE
Bowling Bash (with Bow)

### ISSUE THREAD

**Issue by Rorrie** [GMBoreas/trocalculator#267]
I read the following issue https://github.com/GMBoreas/trocalculator/issues/251 and saw this was "fixed" however my calculations vs in-game are different!

**Calc Setup:**
https://calc.talonro.com/?caCbLbhabbCaVbKababEkagjCaaaaaaaaae5aaaaaaaaahkaawjfZeAeTc7fchUflgZvsaavsaaaaaaaiakakaaaabkkaaaaaabokaaajtaaaaHaaaaaaaaa

With this setup, the aim is to 1 shot Piranha with Bowling Bash without Impositio Manus. I tried the EXACT same build/gears in-game several times to be sure and the calculated result was way off.

**Rental Rudra**
Calculator: 8111 x 2hit **(100% 1-shot)**
In-game: 6300 x 2hit
In-game + Impositio Manus: 6600 x 2hit

**Comment by Loabox** [comment]
The bowling bash fix isn't actually live yet. I just had a quick test in the development version that has the fix, and the numbers are ~6300-6600 x 2 and ~6600-6900 x 2 with Imposito Manus. Regardless, thanks for bringing this to our attention. This fix along with many others will be live when we release a new version.
