### ISSUE TITLE
[Missing Item] - Xmas Snowman Hat

### ISSUE THREAD

**Issue by gundargerm** [GMBoreas/trocalculator#27]
**Name:** Xmas Snowman Hat (#20030)
**Def:** 4
**Slot:** 0
**Location:** Upper Headgear
**Required Lvl:** 30
**Job:** All Job
**Weight:** 20

**Description:**
INT + 3
DEX + 2
VIT + 3
AGI + 3
Cast Time -10%.
Add a 3% chance of freezing an enemy when receiving Physical Damage.

**Item Script:**
[bonus bInt,3; bonus bDex,2; bonus bVit,3; bonus bAgi,3; bonus bCastrate,-10; bonus2 bAddEffWhenHit,Eff_Freeze,300;], [], []

**Comment by zonesoldier** [comment]
Added. Closing Issue.

**Comment by gundargerm** [comment]
![bug_1](https://user-images.githubusercontent.com/6234402/41267503-ec52c000-6e25-11e8-8df8-a469e0f71820.JPG)
