### ISSUE TITLE
Calculator Using Renewal FLEE UP / NPC_AGIUP

### ISSUE THREAD

**Issue by TTheStranger** [GMBoreas/trocalculator#272]
[https://irowiki.org/classic/NPC_AGIUP](https://irowiki.org/classic/NPC_AGIUP) pre-renewal FLEE UP
[https://irowiki.org/wiki/NPC_AGIUP](https://irowiki.org/wiki/NPC_AGIUP) renewal FLEE UP

According to IRO classic wiki , FLEE UP level 5 should increase a monster's agi by 300%, which would result in their FLEE increasing by twice their agi. When calculating on Valkyrie Randgris (mob id 1751), who has 120 agi, this means her flee should increase by 240. When FLEE UP is active, her perfect hit (PH) stat should be

PH (FLEE UP) = level + agi + 20 = 99 + (120)(300%) + 20 = 479

However, the calculator gives a different result of 458. After toying around with some other mobs, the calculator is using the formula:

PH (FLEE UP) = 2PH - 20 = 2level + 2agi + 20 = 2Flee + 20

where PH is the perfect hit required when FLEE UP is inactive.

This is different from what IRO classic wiki states; in fact, it is using the renewal formula for FLEE UP, which doubles the monster's Flee.

![randgris](https://user-images.githubusercontent.com/42041560/43607903-8cf91152-9654-11e8-86f2-607b1883f61f.png)

**Comment by TensaiKato** [comment]
Commited~
