### ISSUE TITLE
Item equipable class incorrect - ID 2721

### ISSUE THREAD

**Issue by ss4w** [GMBoreas/trocalculator#275]
Thief's Medallion can be used by Ninjas too :)

**Comment by Loabox** [comment]
Is this tested in-game? The item description says thief class.

**Comment by Loabox** [comment]
Hmm I will see if I can check with another GM. The panel DB is atrociously outdated, so it's best to check the actual in game items at the BG vendor.

**Comment by Loabox** [comment]
You are right it was fixed last reboot and the item description will be updated in the future.
Fixed and awaiting PR.

**Comment by TensaiKato** [comment]
Commited~
