### ISSUE TITLE
[Missing Item] - Xmas Rudolph Santa Hat

### ISSUE THREAD

**Issue by gundargerm** [GMBoreas/trocalculator#28]
**Name:** Xmas Rudolph Santa Hat (#8801)
**Def:** 2
**Slot:** 0
**Location:** Upper Headgear
**Required Lvl:** 1
**Job:** All Job
**Weight:** 40

**Description:**
All Stats +1.
Cast Time -5%.
Increase effectiveness of healing items by 5%.
Increases damage on Boss monsters by 5%.
Increases damage on Non-Boss monsters by 5%.

**Item Script:**
[bonus bAllStats,1; bonus bCastrate,-5; bonus2 bAddItemHealRate,IG_Recovery,5; bonus2 bAddRace,RC_NonBoss,5; bonus2 bAddRace,RC_Boss,5; bonus3 bAddMonsterDropItem,14550,RC_NonBoss,100;], [], []

**Comment by zonesoldier** [comment]
Added. Issue closed.
