### ISSUE TITLE
[Bug] No cast time reduction on Tegron

### ISSUE THREAD

**Issue by kutsuru** [GMBoreas/trocalculator#285]
Hi,

Tegron[2] (ID:1181)
Script:
[bonus bFlee2,10; if (JobLevel>=70) autobonus "{ bonus bBaseAtk,50; }",10,10000,BF_WEAPON,"{ specialeffect2 EF_POTION_BERSERK; }"; if (getrefine() > 8) { bonus bCastrate,-20; bonus bDelayRate,-20; }]

Missing behaviour:
if (getrefine() > 8) { **bonus bCastrate,-20**; bonus bDelayRate,-20; }
The reduction of cast delay is well included but not for the cast time

--
Kutsu

**Comment by Loabox** [comment]
Fixed. Awaiting PR.

**Comment by kutsuru** [comment]
Good job !
