### ISSUE TITLE
[Missing effect] Whistle P.D effect

### ISSUE THREAD

**Issue by Rafekxx** [GMBoreas/trocalculator#287]
Hello!

When I was recently making 100 P.D clown at calculator I've noticed that skill A Whistle isn't displaying bard's LUK for flooring the song. In fact it didn't affect P.D at all and the only option for it was flee enchant.

Here is formula for A Whistle's P.D: Base Whistle bonus + Floor (LUK/10) + Music Lessons Lv/2

Thank you for reading!

**Comment by TensaiKato** [comment]
Done, awaiting PR~
