### ISSUE TITLE
[Drake Card Additional skill]

### ISSUE THREAD

**Issue by Metaphallica** [GMBoreas/trocalculator#288]
The Acquired Skill from Drake Card only goes up to level 1 it appears, while the DB says the card gives level 4.

**Comment by TensaiKato** [comment]
Hello there,

Couldn't find it.

![image](https://user-images.githubusercontent.com/39836231/49734785-97e78480-fc6c-11e8-953b-d351024b7d71.png)

**Comment by kutsuru** [comment]
Cannot reproduce.
