### ISSUE TITLE
[Missing item/monsters][Calcul false 2nd hand]

### ISSUE THREAD

**Issue by Takhui** [GMBoreas/trocalculator#289]
Add :  Oxygen Bottle [1] ID #21114 / Monsters OGH

Modify the calcul damage for a +10 main gauche (totally false).

**Comment by TensaiKato** [comment]
Done:
- Oxygen Bottle;
- Summer Sandals;
- Surfer Swimsuit;

Need to elaborate more on the Main Gauche problem

**Comment by TensaiKato** [comment]
Done items~

**Comment by Takhui** [comment]
I dont see any change on the calc for missing items

**Comment by kutsuru** [comment]
Looks like Kato did not submit a pull request for new items, anyway were added in the last pull request, I will close this issue, open a dedicated one for the off-hand damage computation please.
