### ISSUE TITLE
[Missing Item] - Lord of the Dead Helm

### ISSUE THREAD

**Issue by gundargerm** [GMBoreas/trocalculator#29]
**Name:** Lord of the Dead Helm (#18574)
**Def:** 5
**Slot:** 1
**Location:** Upper, Middle Headgear
**Required Lvl:** 70
**Job:** All Job
**Weight:** 100

**Description:**
MDEF + 5.
Increases physical damage against boss-type monsters by 10%
Receive 5% more damage from all monsters.

**[Refine Rate 5~10]**
Increase damage on Boss monster by 1% for every refine.
**[+ Abysmal Knight Card]**
Increase damage on Boss monster by 5%.

**[Refine Rate 6~10]**
Receive 1% more damage from all monsters for every refine.

**Item Script:**
[bonus bMdef,5; bonus2 bAddRace,RC_Boss,10; bonus2 bSubRace,RC_NonBoss,-5; bonus2 bSubRace,RC_Boss,-5; bonus2 bSubRace,5,-5; if(getrefine()>=5) bonus2 bAddRace,RC_Boss,getrefine(); if(isequipped(4140)) { bonus2 bAddRace,RC_Boss,5; if(getrefine()>=6) { bonus2 bSubRace,RC_NonBoss,-getrefine(); bonus2 bSubRace,RC_Boss,-getrefine(); bonus2 bSubRace,5,-getrefine(); }}], [], []

**Comment by nattwara** [comment]
done

**Comment by slaptro** [comment]
Merged to master.
