### ISSUE TITLE
[Missing item] Add Saiyan Hair on calc

### ISSUE THREAD

**Issue by Takhui** [GMBoreas/trocalculator#292]
Add Saiyan Hair on calc 

Thx

**Comment by kutsuru** [comment]
ID #18740
**Location:** Upper Headgear
**Description:**

> People wearing this hairstyle will suddenly get immense power and speed!
> STR + 3, ASPD + 7%.

**Script:** [bonus bStr,3; bonus bAspdRate,7;], [], []

**Comment by kutsuru** [comment]
Fixed, awaiting PR.
