### ISSUE TITLE
[Missing Item] - Legionnaire Hat

### ISSUE THREAD

**Issue by gundargerm** [GMBoreas/trocalculator#30]
**Name:** Legionnaire Hat (#5418)
**Def:** 4
**Slot:** 1
**Location:** Upper Headgear
**Required Lvl:** 0
**Job:** All Job
**Weight:** 40

**Description:**
STR + 1.
Increases physical damage against boss type monsters by 3%.
Increases physical damage against non-boss type monsters by 3%.

**Item Script:**
[bonus bStr,1; bonus2 bAddRace,RC_NonBoss,3; bonus2 bAddRace,RC_Boss,3;], [], []

**Comment by zonesoldier** [comment]
Added, Sent to master. Issue Closed.
