### ISSUE TITLE
[Missing item] Ribbon Magician Hat

### ISSUE THREAD

**Issue by victorgawk** [GMBoreas/trocalculator#303]
Itemid: 18641
Name: Ribbon Magician Hat
Location: Upper Headgear
Atk: N/a
Def: 2
Required LVL: 1
Slot: 1
Weight: 20
Job: Every Job except Novice
Description:
A decorated magician hat.
INT+3, MATK+5%, SP +
50.

**Comment by zonesoldier** [comment]
Your missing some info. 
,[1674,50,0,2,1,1,20,1,"Ribbon Magician Hat","","A decorated magician hat.",4,3,89,5,14,50,0]

**Comment by zonesoldier** [comment]
victorgawk finished it, merged to master.
