### ISSUE TITLE
[BUG] Wakwak card ATK bonus displayed, but not included in battle calculation

### ISSUE THREAD

**Issue by Hatfun** [GMBoreas/trocalculator#307]
https://forum.talonro.com/topic/28330-talonros-calculator-project/?do=findComment&comment=281941

There are 2 areas where ATK bonus need to be implemented: the displaying part and the calculation part. Currently it's only calculated to display the ATK in the stat table, but not actually used in battle calculation.

**Comment by zonesoldier** [comment]
issue resolved.
