### ISSUE TITLE
[Missing item] Helm Of Dragon General

### ISSUE THREAD

**Issue by Isilla666** [GMBoreas/trocalculator#310]
Once in control of a dragon, this helm will give you protection.
Gives you the power to reach for a dragon's heart.
You will do 5% more physical and magical damage to Dragon-type monsters.
Add a 5% resistance to Dragon-type monsters.
Mdef + 3
Item Class : Headgear
Defense : 3
Location : Upper
Weight : 20
Required Level : 10
Jobs : All Jobs
ID : 18555

**Comment by kutsuru** [comment]
Fixed, awaiting PR.
