### ISSUE TITLE
[Bug] Guardian Stone is boss type

### ISSUE THREAD

**Issue by victorgawk** [GMBoreas/trocalculator#311]
![image](https://user-images.githubusercontent.com/6736720/67159172-87397d80-f317-11e9-8241-efc1a2c90134.png)
Guardian Stone is boss type but the calculator is wrongly considering as non-boss

**Comment by kutsuru** [comment]
Fixed, awaiting PR.

**Comment by victorgawk** [comment]
lol thanks @kutsuru 👍
