### ISSUE TITLE
[Feature] Battle calculation should ideally be based on the ATK used for display

### ISSUE THREAD

**Issue by Hatfun** [GMBoreas/trocalculator#318]
There are 2 separate calculations, one for the ATK displayed, one for the actual battle calculation, causing multiple bugs (same problem as Wakwak previously) 
Not sure what was the reason behind this separation (maybe because of how dual weapon is handled? didn't look at that), but it would be great if calculation for battle damage was directly based on the ATK stats instead of being recalculated. that would avoid all those kind of bugs.

**Comment by kutsuru** [comment]
Fixed, awaiting for PR.
C_ATK is now using n_tok[17] and n_tok[87]
I_ATK is now using wImp

Regarding n_tok[87], still need to figure out where/when exactly it should be applied (should it take in consideration the weapon attack for example ?)
