### ISSUE TITLE
[Missing Item] - Entweihen Hairband

### ISSUE THREAD

**Issue by gundargerm** [GMBoreas/trocalculator#33]
**Name:** Entweihen Hairband (#18804)
**Def:** 2
**Slot:** 1
**Location:** Upper Headgear
**Required Lvl:** 10
**Job:** All Job
**Weight:** 30

**Description:**
INT + 1
DEX + 1
MATK + 1%
**[Refine Rate 5~10]**
For every refine, add +1% MATK.

**When equipping [Entweihen Hairband]+[Dark Thorn Staff] at the same time:**
**[Refine Rate 5~10 Dark Thorn Staff]**
For every 2 refines on the Dark Thorn Staff, add +10 MATK

**Item Script:**
[bonus bInt,1; bonus bDex,1; bonus bMatkRate,1; if(getrefine()>4) bonus bMatkRate,getrefine()-4;], [], []

**Comment by zonesoldier** [comment]
working on it.

**Comment by zonesoldier** [comment]
Added to master file. Issue closed.
