### ISSUE TITLE
[Missing Monster] World Hunters

### ISSUE THREAD

**Issue by kutsuru** [GMBoreas/trocalculator#338]
Missing:
- Aegir
- Orme
- Dark Randgris
- Dark dragon

**Comment by Takhui** [comment]
AT monsters missing in calc :
Floor 4 : Flame Hound , Ravager
Floor 5 : Garmr and Skoll
Floor 6 : Valhalla Justice, Valhalla Sentinel, Valhalla Sanctum
Floor 7 : Valhalla Justice
Floor 8 : Valhalla Redeemer, Valhalla Sentinel, Valhalla Sanctum
Floor 10 : Loki , Loki's Adherents
Floor 16 : Valhalla Justice, Valhalla Sanctum
Floor 17 : Valhalla Sentinel, Valhalla Sanctum
Floor 19 : Aegir
Floor 28 : Skaadi , Skaadi's Disciple
Floor 29 : Modgud , Saga, Aliaska

**Comment by Takhui** [comment]
+ Lucia (boss halloween)
