### ISSUE TITLE
[Bug] Pvp links are not working

### ISSUE THREAD

**Issue by victorgawk** [GMBoreas/trocalculator#346]
Example:

[https://calc.talonro.com/pvp.html?_w43CjF0KwoQwDMKEwq9UWcOEw6d9KMKIegLDnyYxw77CpFBdRMOcw57DnlTDsA5+MMOJwpBMw4JIw5TDkcKCAR86wqkBQcK/AcO7wr9fEHEjJR7DlsOEw65UdnJsFcOHwpEnH8O9w5RuDsOIwppFBRpCwrDCpMKJwrLDscO5QRrDs8Oxw49Gw5YUw7PCvRfCqzUKwrzChQs](https://calc.talonro.com/pvp.html?_w43CjF0KwoQwDMKEwq9UWcOEw6d9KMKIegLDnyYxw77CpFBdRMOcw57DnlTDsA5+MMOJwpBMw4JIw5TDkcKCAR86wqkBQcK/AcO7wr9fEHEjJR7DlsOEw65UdnJsFcOHwpEnH8O9w5RuDsOIwppFBRpCwrDCpMKJwrLDscO5QRrDs8Oxw49Gw5YUw7PCvRfCqzUKwrzChQs)

pvm links are working, it's just the pvp ones that aren't.

**Comment by victorgawk** [comment]
Reported by @Svar0g#2712 from TalonRO discord

**Comment by kutsuru** [comment]
Yep already fixed
