### ISSUE TITLE
[Missing Item] - Maiden Hat

### ISSUE THREAD

**Issue by gundargerm** [GMBoreas/trocalculator#37]
**Name:** Maiden Hat (#5211)
**Def:** 2
**Slot:** 1
**Location:** Upper Headgear
**Required Lvl:** 20
**Job:** All Job
**Weight:** 20

**Description:**
STR + 1
INT + 1
MDEF + 7
ATK + 2%
MATK + 2%
Heal effectiveness increased by 5%

**[Refine Rate 7~10]**
Additional ATK + 1%
Additional MATK +1%
Additional Heal effectiveness + 1%

**Item Script:**
[bonus bMdef,7; bonus bStr,1; bonus bInt,1; bonus2 bAddRace,RC_NonBoss,2; bonus2 bAddRace,RC_Boss,2; bonus bMAtkRate,2; bonus bHealPower,5; if(getrefine() >= 7) { bonus2 bAddRace,RC_NonBoss,1; bonus2 bAddRace,RC_Boss,1; bonus bMAtkRate,1; bonus bHealPower,1; }], [], []

**Comment by zonesoldier** [comment]
Item added. Issue Closed.
