### ISSUE TITLE
[Bug] Weaponry Research

### ISSUE THREAD

**Issue by Isilla666** [GMBoreas/trocalculator#383]
https://calc.talonro.com/?_w4XCjMONDcOCMBTCg1dhA8K4w4DCvSAQSMKtwqAqC8OYSR55TcOaw7ITFMKxPQUEK8Oww4nCkn3CsG1QwrDCpHIHw48CMxDDnCjDgMOsUMK3D1MDbsKOLz4AWcK5w4jDqxR9wpMGQMOawpPClWrDtMOSwqzDnsKVSAYRw4EoMMKEw49OLsOBwojDscOVK2/DhcO+w75AHsOYw7DDiD3DvsOKw7LCrsORTnp0bmrDncONXMO1wpx0w6jCnw

Why I have Hit Ratio 100% against Ifrit with 283 hit, but perfect hit for Ifrit is 299.

**Comment by kutsuru** [comment]
Normal behaviour

Explicit HIT bonus
`if((skill=pc_checkskill(sd,BS_WEAPONRESEARCH))>0)`
`	base_status->hit += skill*2;`

Implicit HIT ratio bonus
`// Weaponry Research hidden bonus`
`if ((skill = pc_checkskill(sd,BS_WEAPONRESEARCH)) > 0)`
`	hitrate += hitrate * ( 2 * skill ) / 100;`
