### ISSUE TITLE
[Bug] Extended Info - Cant Change Any Property

### ISSUE THREAD

**Issue by ugurozturk** [GMBoreas/trocalculator#387]
It gets reset whenever i try to change any property

![calc talonro](https://user-images.githubusercontent.com/7994408/100480651-eebd2180-3102-11eb-840f-5966e9f6bb75.gif)

**Comment by kutsuru** [comment]
Issue known, thanks for having a look into it, I will close it with Gawk's PR being accepted

**Comment by kutsuru** [comment]
Fixed in master branch, but re-introduced an update issue regarding magic damage modifiers
