### ISSUE TITLE
[Missing Item] - Bangungot Agimat Tattoo

### ISSUE THREAD

**Issue by gundargerm** [GMBoreas/trocalculator#39]
**Name:** Bangungot Agimat Tattoo (#2911)
**Def:** 0
**Slot:** 0
**Location:** Accessory
**Required Lvl:** 1
**Job:** All Job
**Weight:** 10

**Description:**
+4% effectiveness to all healing skills done to others
+7% effectiveness to all healing skills received from others 

**Item Script:**
[bonus bHealPower,4; bonus bHealPower2,7;], [], []

**Comment by gundargerm** [comment]
About the description, I am a bit confused  here:

**Bangungot Agimat Tattoo's item description as shown on itemdb tells us:**
Increases recovery rate of **Healing skills and items** on yourself by 7%.

It mentions about recovery rate of Healing skills and Healing items, while the script used is [bonus bHealPower2] which refers to "Increases heal amount if you are healed by any skills by n%" ONLY.

And in order to increase recovery rate of Healing items you should attach [bonus bAddItemHealRate], am I right?

**Comment by zonesoldier** [comment]
Until this object is updated on the database i'll leave out the 7% heal from items out of it.

Added Item, Closing Issue.
