### ISSUE TITLE
[Missing Item] - Evolved pets 

### ISSUE THREAD

**Issue by TensaiKato** [GMBoreas/trocalculator#4]
Need to elaborate the list, but Evolved pets are not shown.

**Comment by gundargerm** [comment]
**==========================================
Evolved Pets
==========================================**
- Alicel [DEF +1, Demi-Human Resistance +1%]
- Am Mut [MATK +2%]
- Bradium Golem [MHP +250, FLEE +10]
- Choco [ASPD +3%]
- Condor [STR +3, ATK +6]
- Desert Wolf [INT +2, MSP +100]
- Draco [VIT +1, MDEF +1, ASPD +2%]
- Evil Marionette [MHP+50, MSP+10, HP & SP Recovery +10%]
- Giant Whisper [FLEE +10, Perfect Dodge +1]
- Grand Peco [MHP +500, MSP +25]
- High Orc [ATK +2%]
- Jaguar [ASPD +5%]
- Savage [MHP +300, VIT +5]
- Yao Jun [INT+1, VIT+1, DEF+1, MDEF+1, MHP+150, MSP+10]

**Comment by gundargerm** [comment]
**==========================================
Implemented-but-Unlisted Pets on Current Calculator
==========================================**
- Mini Ice Titan [ASPD +1%. Chance to Freeze enemy when doing physical attakcs]
- Aqua Elemental [ASPD +1%, Water Resistance +2%]
- Bathory [VIT +1, Shadow Resistance +3%]
- Beary Punny Bear [FLEE +5, STR +1, INT +1, DEX +1]
- Blue Unicorn [INT +1, Holy Resistance +2%]
- Chepet [LUK +1, Holy Resistance +2%]
- Cornus [ASPD +2%, ATK -1%]
- Domovoi [AGI +2]
- Dumpling Child [Neutral Resistance +1%]
- Eggyra [AGI +3]
- Ferus [Increase damage against Dragon by 5% & Undead by 2%]
- Freezer [STR +1, Water Resistance 2%]
- Garden Keeper [INT +1, AGI +1, Holy Resistance +2%]
- Galapago [AGI +2, LUK +4 if equipped with Galapago Cap]
- Gibbet [Perfect Dodge +1, AGI +2, Shadow Resistance +1%]
- Hell Poodle [DEF +1, VIT +2, Shadow Resistance +1%]
- Hylozoist [LUK +2, Ghost Resistance +2%]
- Little Poring [LUK +2, CRIT +1]
- Lude [INT +2, Ghost Resistance +2%]
- Mavka [Earth Resistance +2%, Damage against Fire Monsters +1%]
- Mermaid [INT +1, DEX +1]
- Pandaring [VIT +2, INT +4 if equipped with Panda Hat]
- Pouring [STR +2]
- Sedora [LUK +2]
- Snow Bunny [ASPD +1%, DEX +1]
- Snowier [ASPD +1%, STR +1]
- Teddy Bear [VIT +2]
- Tiyanak [STR +1, LUK +1, Shadow Resistance +2%]
- Chung E [DEF +1, Demi-Human Resistance +1%]
- Tiny Agni [Physical/Magical Damage against Fire Monsters +2%]
- Tiny Aqua [Physical/Magical Damage against Water Monsters +2%]
- Tiny Ventus [Physical/Magical Damage against Wind Monsters +2%]
- Agni [Physical/Magical Damage against Fire Monsters +2%, Fire Resistance +2%]
- Ventus [Physical/Magical Damage against Wind Monsters +2%, Wind Resistance +2%]
- Eira [Increases effectiveness of your Heal, Sanctuary and Potion Pitcher by 5%, 2% Chance of gaining 5% of the damage inflicted on an enemy as HP]
- Aqua [Physical/Magical Damage against Water Monsters +2%, Water Resistance +2%]
- Angry Penguin [Increase effectiveness of your Heal, Sanctuary and Potion Pitcher by 3%]
- Baby Skoll [[Swordman, Thief, Merchant class] SP Regeneration +20%, [Archer, Acolyte, Magician class] HP Regeneration +20%, [Extended Class]HP/SP Regeneration +10%, Perfect Dodge +3]
- Ballooling [Increases effectiveness of Heal, Sanctuary and Potion Pitcher on yourself by 2%]
- Jejeling [VIT +2, DEX +4 if equipped with Baseball Cap]
- Elephant [Perfect Dodge +2, VIT +3]
- Gorilla [STR +3, VIT +3]
- Lion [FLEE +5, VIT +3]
- Rhino [ATK +5, VIT +3]
- Little Fatum [ASPD +1%, DEX +1]
- Lucky Case [[Mage, Archer, Acolyte Class] MHP +175, Perfect Dodge +1, [Swordman, Merchant, Thief Class] MSP +50, VIT +2]
- Miming [INT +1, VIT +1, Increases effectiveness of your Heal, Sanctuary and Potion Pitcher by 5%]
- Scatleton [VIT +1, Shadow Resistance +1%, Ghost Resistance +2%]
- Skelion [MHP +250, MDEF +1, ASPD +2%, Ghost Resistance +2%]
- Tikbalang [Increase damage to Bakonawa, Bangungot and Buwaya by 10%]
- Toucan [DEX +1, FLEE +5]
- White Goat [+1.5% chance to cast Level 2 Bash when doing a physical attack, Increases the healing value of Carrots by 100%]
- Wild Rider [AGI +2, DEX +3, if equipped with Drooping Cat]

**Comment by gundargerm** [comment]
**==========================================
Typo/Wrong Name & Description
==========================================**
- Rice Cake > Rice Cake [Neutral Resistance +1%]
- Zealotus > Zherlthsh [MATK +2%, Magical Damage against Demi-Human +2%]

**Comment by TensaiKato** [comment]
Done, awaiting commit

**Comment by TensaiKato** [comment]
Commited
