### ISSUE TITLE
[Missing Item] - Cat Hand Glove

### ISSUE THREAD

**Issue by gundargerm** [GMBoreas/trocalculator#40]
**Name:** Cat Hand Glove (#2873)
**Def:** 0
**Slot:** 1
**Location:** Accessory
**Required Lvl:** 1
**Job:** All Job
**Weight:** 10

**Description:**
VIT +1
AGI +1
LUK +1

**Item Script:**
[bonus bAgi,1; bonus bVit,1; bonus bLuk,1;], [], []

**Comment by zonesoldier** [comment]
Item Added. Issue Closed.
