### ISSUE TITLE
Little off

### ISSUE THREAD

**Issue by IMrHarem** [GMBoreas/trocalculator#404]
![image](https://user-images.githubusercontent.com/91565859/135150126-1c9ba00d-282f-4999-81b3-1bdc57b6e82e.png)

Sanctuary and Healing With Bless Are not the same At Talon calculator

Level 7 Sanctuary Gives 854 Heal Not Calculated

Level 10 Heal Stay the right Calculated  2494

https://calc.talonro.com/?_w43CjEsOQDAYwoTDjyQuwoFaWMOYWH4/wq3DksOGw4bDm8Opw5XDqw4mwpnDjCTDs8Kow5lEwolmQcKoJMKXMWgPbsK3wrzDsMKOLn7CrHXCsAbDjsKrVnBkIUx1ZybCgy/Dn3ZrbhHDt8ONw4MfDMONw6USIsO+woLCpDgB

**Comment by kutsuru** [comment]
Hi @IMrHarem ,

Thanks for the report, issue was not related to blessing as INT is not impacting Sanctuary healing power, but due to a remnant of previous code which lead to counting staff of recovery bonus twice.

**Comment by IMrHarem** [comment]
*Plus 7 Staff of recovery just only heal 853 ingame*
[image: image.png]
