### ISSUE TITLE
[Missing Item] - Bunch of Carnations

### ISSUE THREAD

**Issue by gundargerm** [GMBoreas/trocalculator#42]
**Name:** Bunch of Carnations (#2646)
**Def:** 0
**Slot:** 0
**Location:** Accessory
**Required Lvl:** N/A
**Job:** All Job
**Weight:** 10

**Description:**
All Stats + 3

**Item Script:**
[bonus bStr,3; bonus bAgi,3; bonus bVit,3; bonus bInt,3; bonus bLuk,3; bonus bDex,3;], [], []

**Comment by zonesoldier** [comment]
Item Added. Issue Closed.
