### ISSUE TITLE
[Missing Item] - Buwaya Agimat Tattoo

### ISSUE THREAD

**Issue by gundargerm** [GMBoreas/trocalculator#43]
**Name:** Buwaya Agimat Tattoo (#2907)
**Def:** 0
**Slot:** 0
**Location:** Accessory
**Required Lvl:** 1
**Job:** All Job
**Weight:** 10

**Description:**
MATK + 7%
Cast Time - 8%

**Item Script:**
[bonus bMatkRate,7; bonus bCastRate,-8;], [], []

**Comment by zonesoldier** [comment]
Item Added. Issue Closed.
