### ISSUE TITLE
[Possible Weight fixes for Skill Spiral Pierce, some offensive Shield sk﻿i﻿ll﻿s]

### ISSUE THREAD

**Issue by zonesoldier** [GMBoreas/trocalculator#44]
not only for the weight limit function, also for some skills that consider weight as a factor, like Spiral Pierce and some offensive Shield skills. M a r x left this up in the forum.

Might be something to look into the future with the Calc and see if the math is right for the skills.

**Comment by kutsuru** [comment]
Shield Chain damage computation was fixed (related issue #341)
Shield Boomerang damage computation seems correct
Spiral Pierce was not taking into consideration spear mastery in the damage computation, fixed through this issue
