### ISSUE TITLE
[Strange Behavior] - Forging/Brewing

### ISSUE THREAD

**Issue by TensaiKato** [GMBoreas/trocalculator#5]
========= NEED TO CONFIRM THIS ===========

Forging/Brewing﻿ Info shows wrong final success chance for Fat R/Y/W Pot, Alcohol, Acid Bottle, Bottle Grenade final success rate is shown with variable rate (+-5% in brackets) but I can confirm at least for these named recipes that there is no variable success rate just the fixed rate from stats and skills ﻿

**Comment by slaptro** [comment]
No issue found after verifying againt skill.cpp

**Comment by slaptro** [comment]
Need to remove success cap in calculations

**Comment by slaptro** [comment]
Updated brewing calculations; should now be a lot more accurate and informative.
