### ISSUE TITLE
[Missing Item] - Malangdo Enchants

### ISSUE THREAD

**Issue by TensaiKato** [GMBoreas/trocalculator#6]
Add the entire enchants, need to elaborate the + and item list.

**Comment by TensaiKato** [comment]
[Daggers]
Swordbreaker #1224
Mailbreaker #1225
Weeder Knife #1227
Kitchen Knife #1229
Assassin Dagger #1232
Exorciser #1233
Azoth #1235
Sucsamad #1236
Grimtooth #1237
Princess Knife #1240
Cursed Dagger #1241
Dagger of Counter #1242
Holy Dagger #1244
Krieg Dagger[3] #13046
Voina Dagger [2] #13047
Black Wing [1] #13061
Fortune Sword #1223
Combat Knife #1228
Moonlight Dagger #1234
Ice Pick #1230
Bazerald #1231
Ancient Dagger #13062

**Comment by TensaiKato** [comment]
Possible Enchants

HP+100, HP+200,HP+300
SP+50,SP+100
STR+1,STR+2,STR+3
AGI+1,AGI+2,AGI+3
VIT+1,
INT+1,INT+2,INT+3
DEX+1,DEX+2,DEX+3
LUK+1
ASPD+3%
Fighting Spirit 1,2,3,4,5,6,7,8
Sharp 1,2,3,4,5
Expert Archer 1,2,3,4,5,6
Spell 1,2,3,4,5,6

**Comment by slaptro** [comment]
Missing Enchants:
Spell 7 (6% Wind Magic DMG)
ATK+1%
MATK+1%
MATK+2%

Impossible Enchants:
HP+300
Fighting Spirit 1
Fighting Spirit 2
Fighting Spirit 3
Sharp 1
Expert Archer 1

**Comment by TensaiKato** [comment]
Done~
