### ISSUE TITLE
[Missing Item] - Enhanced Corsair

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#62]
**ItemID:** 18765
**Name:** Enhanced Corsair [1]
**Location:** Upper Headgear
**Def:** 5
**Required Lvl:** 50
**Slot:** 1
**Weight:** 50
**Job:** Every job except Novice

**Description:**
A flamboyant hat worn only by the strongest of pirates.
VIT + 1, Maximum HP + 5%
Reduce 1% damage from Neutral type attacks.
[Refine Rate 5~7+]
Maximum HP + 1%
[Refine Rate 8+]
Maximum HP + 2%
Reduce another 1% damage from Neutral type attacks.

**Item script:**
[if(getrefine()>4) { set .@i,((getrefine()>7)?5:getrefine()-4); } bonus bVit,1; bonus bMaxHPrate,5+.@i; bonus2 bSubEle,Ele_Neutral,((getrefine()>7)?2:1);], [], []

**Note**: 
Just an example on the Maximum HP bonus and other similar "Enhanced" item bonuses:
refine < 5, max HP +5%
refine = 5, max HP +6%
refine = 6, max HP +7%
refine = 7, max HP +8%
refine > 7, max HP +10%

**Comment by nattwara** [comment]
done

**Comment by slaptro** [comment]
Merged to master.
