### ISSUE TITLE
[Missing Item] - Enhanced Bone Helm

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#63]
**ItemID:** 18768
**Name:** Enhanced Bone Helm [1]
**Location:** Upper Headgear
**Def:** 5
**Required Lvl:** 70
**Slot:** 1
**Weight:** 240
**Job:** Swordman Class, Merchant Class

**Description:**
An incredibly heavy, yet almost impenetrable helmet constructed of bone.
Increases damage received from Shadow Property attacks by 15%.
Decreases damage received from Neutral Property attacks by 1%.
Every refine level past +4 until +8 reduces DEF by 1 and decreases damage received from Neutral Property attacks by another 1%.

**Item script:**
[bonus2 bSubEle,Ele_Dark,-15; if(getrefine()>4) { set .@i,((getrefine()>7)?4:getrefine()-4); } bonus2 bSubEle,Ele_Neutral,1+.@i; bonus bDef,-.@i;], [], []

**Comment by nattwara** [comment]
done

**Comment by slaptro** [comment]
Merged to master.
