### ISSUE TITLE
[Missing Item] - Enhanced Helm of Angel

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#65]
**ItemID:** 18766
**Name:** Enhanced Helm of Angel [1]
**Location:** Upper Headgear
**Def:** 5
**Required Lvl:** 74
**Slot:** 1
**Weight:** 160
**Job:** 2nd Class or above

**Description:**
A wondrous helmet adorned with angel wings that was made by a smithing genius.
AGI + 1, LUK + 1, MDEF + 3, ASPD + 5%
[Refine Rate 5~6+]
AGI + 1, LUK + 1, MDEF + 1
[Refine Rate 7+]
ASPD + 1

**Item script:**
[bonus bAspdRate,5; bonus bAgi,1+((getrefine()>4)?((getrefine()>5)?2:1):0); bonus bLuk,1+((getrefine()>4)?((getrefine()>5)?2:1):0); bonus bMdef,3+((getrefine()>4)?((getrefine()>5)?2:1):0); if (getrefine()>6) { bonus bAspd,1; }], [], []

**Comment by nattwara** [comment]
done

**Comment by slaptro** [comment]
Merged to master.
