### ISSUE TITLE
[Missing Item] - Enhanced Hat of the Sun God

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#66]
**ItemID:** 18767
**Name:** Enhanced Hat of the Sun God [1]
**Location:** Headgear (Upper, Middle)
**Def:** 4
**Required Lvl:** 70
**Slot:** 1
**Weight:** 240
**Job:** 2nd Class or above

**Description:**
A hat that is said to have been worn by the god of the sun.
STR + 3, INT + 2
ATK + 10, MATK + 5%
[Refine Rate 5~6+]
ATK + 4, MATK + 1%
[Refine Rate 7+]
ATK + 6, MATK + 1%
[Refine Rate 8+]
ATK + 6, MATK + 2%

**Item script:**
[bonus bStr,3; bonus bInt,2; if(getrefine()>4) { set .@i,((getrefine()>7)?20:((getrefine()>6)?(getrefine()-6)*14:(getrefine()-4)*4)); set .@j,((getrefine()>7)?5:getrefine()-4); } bonus bBaseAtk,10+.@i; bonus bMatkRate,5+.@j;], [], []

**Comment by nattwara** [comment]
done

**Comment by slaptro** [comment]
Merged to master.
