### ISSUE TITLE
[Missing Item] - Enhanced Variant Shoes

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#67]
**ItemID:** 22014
**Name:** Enhanced Variant Shoes [1]
**Location:** Footgear
**Def:** 3
**Required Lvl:** 85
**Slot:** 1
**Weight:** 50
**Job:** Every Rebirth Job except High Novice

**Description:**
Shoes that seem to be wrong somewhere. The intention of the maker to perfect the shoes can be seen but it seems to be a failure.
Maximum HP / Maximum SP + 12%.

**Item script:**
[bonus bMaxHPRate,12; bonus bMaxSPRate,12;], [], []

**Comment by zonesoldier** [comment]
Item.js

,[#,63,1001,3,0,1,50,85,"Enhanced Variant Shoes","","Shoes that seem to be wrong somewhere. The intention of the maker to perfect the shoes can be seen but it seems to be a failure.",15,12,16,12,0]

Notes for afterwork to be added.

I need to look into the 15 and 16 status to make sure they add in the correct % modifier.

**Comment by zonesoldier** [comment]
Item added, issue closed.
