### ISSUE TITLE
[Missing Card]Detale card

### ISSUE THREAD

**Issue by zonesoldier** [GMBoreas/trocalculator#68]
ID #4386
Location:  Armor

-Add 5% chance of auto casting level 1 Land Protector around the user when the user receives Magical Damage

MDEF - 10

Increases resistance against Freeze status by 50% [ Aegir Helm, Aegir Manteau, Aegir Armor, Aegir Shoes Combo ] Gain full immunity against against Freeze status.

-Database also hasnt been updated about the card.

**Comment by TensaiKato** [comment]
Done, awaiting commit
