### ISSUE TITLE
[Missing Item] - Pajamas Hats

### ISSUE THREAD

**Issue by TensaiKato** [GMBoreas/trocalculator#7]
N﻿ame: Blue Pajamas Hat
Location: Upper-Only Headgear
Def: 2
Required Level: -
Slots: 1
Applicable Job: Every Job
Description:
A cute blue pajama hat, very cuddly. Ensures a good night's rest, giving energy to chase your dreams.

Increases damage by 5%. MATK + 5%.
Script: 
[bonus2 bAddRace,RC_NonBoss,5; bonus2 bAddRace,RC_Boss,5; bonus2 bAddRace2,5,5; bonus bMatkRate,5;], [], []

N﻿ame: Pink Pajamas Hat
Location: Upper-Only Headgear
Def: 2
Required Level: -
Slots: 1
Applicable Job: Every Job
Description:
A cute pink pajama hat, very cuddly. Ensures a good night's rest, giving energy to chase your dreams.

Increases damage by 5%. MATK + 5%.
Script: 
[bonus2 bAddRace,RC_NonBoss,5; bonus2 bAddRace,RC_Boss,5; bonus2 bAddRace2,5,5; bonus bMatkRate,5;], [], []

**Comment by zonesoldier** [comment]
Added.
