### ISSUE TITLE
[Missing Item] - Chilly Spell Book

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#70]
**ItemID:** 1584
**Name:** Chilly Spell Book [2]
**Location:** Weapon
**Type:** Book
**Atk:** 100
**Weapon Lvl:** 4
**Required Lvl:** 90
**Slot:** 2
**Weight:** 100
**Job:** Professor
**Element:** Water

**Description:**
The research of a great Sorcerer is detailed in this book. One of the 4 great elemental books (Cold Volume).
MATK + 20%, DEX + 1.
Add a chance of casting Storm Gust level 2 when doing a physical attack.
Each refine increases Cold Bolt and Storm Gust's attack power by 3%, and increases their SP cost by 5.
Indestructible (except in upgrade attempts)

**Item script:**
[bonus bAtkEle,Ele_Water; bonus bUnbreakableWeapon,0; bonus bMatkRate,20; bonus bDex,1; bonus2 bSkillAtk,"MG_COLDBOLT",(getrefine()*3); bonus2 bSkillAtk,"WZ_STORMGUST",(getrefine()*3); bonus2 bSkillUseSP,"MG_COLDBOLT",-(getrefine()*5); bonus2 bSkillUseSP,"WZ_STORMGUST",-(getrefine()*5); bonus3 bAutoSpell,"WZ_STORMGUST",2,10;], [], []

**Comment by nattwara** [comment]
done

**Comment by slaptro** [comment]
Merged to master.
