### ISSUE TITLE
[Missing Item] - End Sektura

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#71]
**Name:** End Sektura [1]
**Location:** Weapon
**Type:** Two-handed Axe
**Atk:** 250
**Weapon Lvl:** 4
**Required Lvl:** 95
**Slot:** 1
**Weight:** 190
**Job:** Trans Swordman Class, Trans Merchant Class
**Element:** Water

**Description:**
An axe made of artic ice.
Chance of inflicting Curse status when dealing physical damage. Risk of targeting yourself.
Indestructible (except in upgrade attempts).

**Item script:**
[bonus bAtkEle,Ele_Water; bonus bUnbreakableWeapon,0; bonus2 bAddEff,Eff_Curse,20; bonus2 bAddEff2,Eff_Curse,10;], [], []

**Comment by zonesoldier** [comment]
Item Added. Issue Closed.
