### ISSUE TITLE
[Missing Item] - Ygnus Stale

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#72]
**Name:** Ygnus Stale [1]
**Location:** Weapon
**Type:** Two-handed Axe
**Atk:** 250
**Weapon Lvl:** 4
**Required Lvl:** 95
**Slot:** 1
**Weight:** 190
**Job:** Trans Swordman Class, Trans Merchant Class
**Element:** Fire

**Description:**
A large axe made by a blacksmith from the fires of a volcano.
Chance of inflicting Bleeding status when dealing physical damage. Risk of targeting yourself.
Indestructible (except in upgrade attempts).

**Item script:**
[bonus bAtkEle,Ele_Fire; bonus bUnbreakableWeapon,0; bonus2 bAddEff,Eff_Bleeding,20; bonus2 bAddEff2,Eff_Bleeding,10;], [], []

**Comment by zonesoldier** [comment]
Item Added. Issue Closed.
