### ISSUE TITLE
[Missing Item] - Rosevine

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#78]
**ItemID:** 1985
**Name:** Rosevine
**Location:** Weapon
**Type:** Whip
**Atk:** 150
**Weapon Lvl:** 4
**Required Lvl:** 92
**Slot:** 0
**Weight:** 100
**Job:** Gypsy

**Description:**
A whip created from a magically enchanted rose that radiates the smell of roses.
When dealing physical damage there is a chance to trigger Wink of Charm.
All Stats + 2, CRIT + 5, MATK + 10%.

**Item script:**
[bonus bAllStats,2; bonus bCritical,5; bonus bMatkRate,10; bonus3 bAutoSpell,"DC_WINKCHARM",1,100;], [], []

**Comment by zonesoldier** [comment]
Item added, skill added, Issue Closed.
