### ISSUE TITLE
[Missing Item] - Agent Katar

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#79]
**ItemID:** 1295
**Name:** Agent Katar [1]
**Location:** Weapon
**Type:** Katar
**Atk:** 170
**Weapon Lvl:** 3
**Required Lvl:** 90
**Slot:** 1
**Weight:** 120
**Job:** Assassin Cross

**Description:**
Add 1 HIT for every 2 LUK.

**Item script:**
[bonus bHit,readparam(bLuk)/2;], [], []

**Comment by zonesoldier** [comment]
Item.js
,[#,11,122,170,3,1,120,90,"Agent Katar","","Add 1 HIT for every 2 LUK.",0]

I'll do the math in the foot.js afterwork.

Notes.

**Comment by zonesoldier** [comment]
Item added and backend stats work. Issue closed.
