### ISSUE TITLE
[Missing Item] - Scarletto Nail

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#80]
**ItemID:** 13070
**Name:** Scarletto Nail
**Location:** Weapon
**Type:** Dagger
**Atk:** 160
**Weapon Lvl:** 4
**Required Lvl:** 92
**Slot:** 0
**Weight:** 50
**Job:** Trans Swordman Class, Trans Merchant Class, Trans Thief Class
**Element:** Fire

**Description:**
MATK + 5%.
Has a chance of activating Stone Curse status while physically attacking and increases the chance with each refine level.

**Item script:**
[bonus bMatkRate,5; bonus bAtkEle,Ele_Fire; bonus2 bAddEff,Eff_Stone,100+(getrefine()*50);], [], []

**Comment by zonesoldier** [comment]
Item.js
,[#,1,0,160,4,0,50,92,"Scarletto Nail","","Has a chance of activating Stone Curse status while physically attacking and increases the chance with each refine level.",89,5,0]

Notes to add afterwork.

I'll look into the activating stone curse status in the foot.js if it applies to the calculator.

**Comment by zonesoldier** [comment]
Done as the effect doesn't show up in the calc menu.
