### ISSUE TITLE
[Missing Item] - Aztoe Nail

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#81]
**ItemID:** 13069
**Name:** Aztoe Nail
**Location:** Weapon
**Type:** Dagger
**Atk:** 160
**Weapon Lvl:** 4
**Required Lvl:** 92
**Slot:** 0
**Weight:** 50
**Job:** Trans Swordman Class, Trans Merchant Class, Trans Thief Class
**Element:** Wind

**Description:**
A dagger that shines blue and enchanted with binding magic.
MATK + 5%.
Has a chance of activating Freeze status while physically attacking and increases the chance with each refine level.

**Item script:**
[bonus bMatkRate,5; bonus bAtkEle,Ele_Wind; bonus2 bAddEff,Eff_Freeze,100+(getrefine()*50);], [], []

**Comment by zonesoldier** [comment]
done, no need to create the effect in the foot.js as the calc doesn't show the freeze effect in its charts.
