### ISSUE TITLE
[Missing Item] - Chrome Metal Sword

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#82]
**ItemID:** 13431
**Name:** Chrome Metal Sword
**Location:** Weapon
**Type:** One-handed Sword
**Atk:** 180
**Weapon Lvl:** 3
**Required Lvl:** 90
**Slot:** 0
**Weight:** 220
**Job:** Trans Swordman Class, Trans Merchant Class

**Description:**
A cold blue dagger crafted from the other world mineral Bradium.
Indestructible (except in upgrade attempts).
AGI + 1, MaxHP - 5%.

**Item script:**
[bonus bAgi,1; bonus bMaxHPrate,-5;], [], []

**Comment by zonesoldier** [comment]
Item.js
,[#,2,0,180,3,0,220,90,"Chrome Metal Sword","","A cold blue dagger crafted from the other world mineral Bradium.<br>Indestructible (except in upgrade attempts).",2,1,15,-5,0]

Notes for Afterwork to add. I will need to check the 15,-5 to see if it shows up at -5% or not.

**Comment by zonesoldier** [comment]
Item Added, Issue closed.
