### ISSUE TITLE
[Wrong Effect/Status] - Chrome Metal Two-Handed Sword

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#83]
Itemid: 1196
Name: Chrome Metal Two-Handed Sword
Location: Two-Handed Sword
Atk: 280
Lvl: 3
Required Lvl: 90
Slot: 0
Weight: 40
Job: **Swordman High, Lord Knight, Paladin**
Description:
A cold blue color sword crafted from the other world mineral Bradium.
Indestructible (except in upgrade attempts).
AGI + 3, MaxHP - 10%.

Only shows up for Swordman High in calc because JobEquipItemOBJ is set to 1101. Changing it to 1051 should fix it.

**Comment by zonesoldier** [comment]
Item updated. Issue closed. Thanks.
