### ISSUE TITLE
[Wrong Effect/Status] - Chameleon Armor

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#84]
Itemid: 2386
Name: Chameleon Armor
Location: Armor
Def: 5
Required Lvl: 70
Slot: 0
Weight: 170
Job: 
Lord Knight, High Priest, High Wizard, Whitesmith, Sniper, Assassin Cross, Paladin, Champion, Professor, Stalker, Creator, Clown/Gypsy
Description:
A mysterious armor that can change its abilities depending on its owner.
Increases HP and SP depending by base level.
Adds a chance immune from all magic skill for 2 sec When receiving magical attack.
[Swordsman, Merchant, Thief]
DEF + 3
[Magician, Archer, Acolyte]
MDEF + 5

Missing stats/effects

**Comment by nattwara** [comment]
done

**Comment by slaptro** [comment]
Fixed and Committed.
