### ISSUE TITLE
[Missing Item] - Wild Rider Card

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#85]
**ItemID:** 4532
**Name:** Wild Rider Card
**Type:** Card
**Location:** Footgear

**Description:**
AGI + 1.
When dealing physical or magic damage there is a 5% chance to cast Level 1 Increase Agility on yourself.

**Item script:**
[bonus bAgi,1; bonus5 bAutoSpell,"AL_INCAGI",1,50,BF_WEAPON|BF_MAGIC,0;], [], []

**Comment by TensaiKato** [comment]
Done, awaiting commit.
