### ISSUE TITLE
[Missing Item] - Red Eruma Card

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#86]
**ItemID:** 4531
**Name:** Red Eruma Card
**Type:** Card
**Location:** Weapon

**Description:**
When dealing magic damage there's a 1.5% chance to cause curse status.

**Item script:**
[bonus3 bAddEff,Eff_Curse,150,ATF_MAGIC;], [], []

**Comment by TensaiKato** [comment]
Done, awaiting commit.
