### ISSUE TITLE
[Missing Item] - Siorava Card

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#87]
**ItemID:** 4530
**Name:** Siorava Card
**Type:** Card
**Location:** Headgear

**Description:**
LUK +2
[Merchant and Merchant Upper Classes]
Every 3 refine on the compounded item adds LUK +1.

**Item script:**
[bonus bLuk,2; if(BaseClass==Job_Merchant){ bonus bLuk,getrefine()/3; }], [], []

**Comment by TensaiKato** [comment]
Done, awaiting commit;
