### ISSUE TITLE
[Missing Item] - Parus Card

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#88]
**ItemID:** 4512
**Name:** Parus Card
**Type:** Card
**Location:** Headgear

**Description:**
Increases effectiveness of Heal skills by +3%.
[Acolyte class]
Every 2 refine adds 1% heal effectiveness.

**Item script:**
[bonus bHealPower,3; if(BaseClass==Job_Acolyte){ bonus bHealPower,getrefine()/2;}], [], []

**Comment by TensaiKato** [comment]
Done, awaiting commit
