### ISSUE TITLE
[Missing Item] - Little Fatum Card

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#89]
**ItemID:** 4511
**Name:** Little Fatum Card
**Type:** Card
**Location:** Weapon

**Description:**
When dealing magic damage there is a 1.5% chance to silence the enemy.

**Item script:**
bonus3 bAddEff,Eff_Silence,150,ATF_MAGIC;], [], []

**Comment by TensaiKato** [comment]
Done, awaiting commit;
