### ISSUE TITLE
[Missing Item] - Nightmare Mimic Card

### ISSUE THREAD

**Issue by slaptro** [GMBoreas/trocalculator#95]
**ItemID:** 4654
**Name:** Nightmare Mimic Card
**Type:** Card
**Location:** Weapon

**Description:**
Increase magical damage against Brute and Undead monsters by 5%.
[+ Nightmare Arclouze Card]
- Reduces damage taken from Brute and Undead monsters by 5%.
- Ignore 20% magic defense of Brute and Undead monsters.

**Item script:**
???

**Comment by zonesoldier** [comment]
Can't find this in the database.

**Comment by slaptro** [comment]
Not in database yet.
